behaviors:
  RobotWalk:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2560
      buffer_size: 81920
      learning_rate: 3.0e-4
      beta: 7.0e-3
      epsilon: 0.2
      lambd: 0.94
      num_epoch: 5
      learning_rate_schedule: constant
    network_settings:
      vis_encode_type: nature_cnn
      normalize: true
      hidden_units: 512
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.85
        strength: 1.0
      curiosity:
        strength: 0.05
        gamma: 0.85
    max_steps: 1e7
